apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-chatbot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lightsspeed/Rag_2026.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: fastrag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
