apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastrag-backend
  namespace: fastrag
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - fastrag
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
